### ISSUE TITLE
gorilla / securecookie archived

### ISSUE THREAD

**Issue by lukehinds** [dghubble/sessions#24]
Hey!

"github.com/gorilla/securecookie" is deprecated. do you plan to port or use a fork? 

Aware that there is no way of reporting a vuln (to what was the gorilla folks) should there one be found.

Like all your work btw and thanks

**Comment by dghubble** [comment]
I'm already aware. When I need a change, I'll fork or reimplement the subset we need. But it's fine for now and low priority

**Comment by dghubble** [comment]
Looks like the upstream found a maintainer again https://github.com/dghubble/sessions/pull/28
