### ISSUE TITLE
Signed secure cookies?

### ISSUE THREAD

**Issue by prologic** [dghubble/sessions#3]
Doesn't look like this library supports secure cookies?

**Comment by dghubble** [comment]
The CookieStore implementation uses `github.com/gorilla/securecookie` for secure cookie creation. You may pass signing secrets and/or encyption secrets to `NewCookieStore(keysPairs ...[]byte)`. Does that clear it up?

* https://github.com/dghubble/sessions/blob/master/store.go#L30
* http://www.gorillatoolkit.org/pkg/securecookie#CodecsFromPairs

**Comment by prologic** [comment]
My only thoughts now are to consider suing https://github.com/andreadipersio/securecookie instead which doesn't pull in gorilla as a dependency?

**Comment by dghubble** [comment]
I have no problem with [gorilla/securecookie](https://github.com/gorilla/securecookie) - I think its reasonable, small, well-tested, and well-used.

It's [gorilla/sessions](https://github.com/gorilla/sessions) that wasn't to my liking. The README goes into some detail, but I rarely ever need multi-cookie sessions, don't want gorilla context, don't want global request mappings, don't want to remember to use their special handler to avoid leaks, etc. So instead I wrote this as a more minimal session system.

**Comment by dghubble** [comment]
Of course, if you prefer that cookie library, feel free to implement the `Store` interface differently from how `CookieStore` does it here or have a fork. Its open source so no reason to settle for unhappiness! :)

I'll close bc I like it as is.

**Comment by prologic** [comment]
I see :) Thanks for the background!
